services:
  homeglow-backend:
    container_name: homeglow-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /mnt/user/appdata/homeglow/data:/app/data
      - /mnt/user/appdata/homeglow/uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=5000
    networks:
      - homeglow-network

  homeglow-frontend:
    container_name: homeglow-frontend
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_OPENWEATHER_API_KEY=${VITE_OPENWEATHER_API_KEY}
        - VITE_REACT_APP_API_URL=${VITE_REACT_APP_API_URL}
    ports:
      - "5050:5050"
    depends_on:
      - homeglow-backend
    networks:
      - homeglow-network

networks:
  homeglow-network:
    driver: bridge
